name: Main
on: [push]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        uses: cypress-io/github-action@v2
        with:
          config-file: ./cypress.config.json
          start: npm run start:ci
          record: true

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy Storybook to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: storybook-static
